#include "update.h"

std::vector<std::string> country_urls = {
    "United States:http://www.floatrates.com/daily/usd.json",
    "Australia:http://www.floatrates.com/daily/aud.json",
    "Switzerland:http://www.floatrates.com/daily/chf.json",
    "Albania:http://www.floatrates.com/daily/all.json",
    "Argentina:http://www.floatrates.com/daily/ars.json",
    "Azerbaijan:http://www.floatrates.com/daily/azn.json",
    "Bangladesh:http://www.floatrates.com/daily/bdt.json",
    "Belarus:http://www.floatrates.com/daily/byn.json",
    "Bosnia and Herzegovina:http://www.floatrates.com/daily/bam.json",
    "Burundi:http://www.floatrates.com/daily/bif.json",
    "Central African Republic:http://www.floatrates.com/daily/xaf.json",
    "Congo, Democratic Republic of the:http://www.floatrates.com/daily/cdf.json",
    "Cuba:http://www.floatrates.com/daily/cup.json",
    "Djibouti:http://www.floatrates.com/daily/djf.json",
    "Egypt:http://www.floatrates.com/daily/egp.json",
    "Fiji:http://www.floatrates.com/daily/fjd.json",
    "Ghana:http://www.floatrates.com/daily/ghs.json",
    "Guinea:http://www.floatrates.com/daily/gnf.json",
    "Honduras:http://www.floatrates.com/daily/hnl.json",
    "Iceland:http://www.floatrates.com/daily/isk.json",
    "Iran:http://www.floatrates.com/daily/irr.json",
    "Jamaica:http://www.floatrates.com/daily/jmd.json",
    "Kenya:http://www.floatrates.com/daily/kes.json",
    "Laos:http://www.floatrates.com/daily/lak.json",
    "Lesotho:http://www.floatrates.com/daily/lsl.json",
    "Lithuania:http://www.floatrates.com/daily/ltl.json",
    "Madagascar:http://www.floatrates.com/daily/mga.json",
    "Maldives:http://www.floatrates.com/daily/mvr.json",
    "Mauritius:http://www.floatrates.com/daily/mur.json",
    "Mongolia:http://www.floatrates.com/daily/mnt.json",
    "Myanmar:http://www.floatrates.com/daily/mmk.json",
    "Netherlands Antilles:http://www.floatrates.com/daily/ang.json",
    "New Zealand:http://www.floatrates.com/daily/nzd.json",
    "Norway:http://www.floatrates.com/daily/nok.json",
    "Panama:http://www.floatrates.com/daily/pab.json",
    "Philippines:http://www.floatrates.com/daily/php.json",
    "Romania:http://www.floatrates.com/daily/ron.json",
    "El Salvador:http://www.floatrates.com/daily/svc.json",
    "Saudi Arabia:http://www.floatrates.com/daily/sar.json",
    "Sierra Leone:http://www.floatrates.com/daily/sll.json",
    "Somalia:http://www.floatrates.com/daily/sos.json",
    "South Sudan:http://www.floatrates.com/daily/ssp.json",
    "Suriname:http://www.floatrates.com/daily/srd.json",
    "Syria:http://www.floatrates.com/daily/syp.json",
    "Thailand:http://www.floatrates.com/daily/thb.json",
    "Tunisia:http://www.floatrates.com/daily/tnd.json",
    "Uganda:http://www.floatrates.com/daily/ugx.json",
    "Uzbekistan:http://www.floatrates.com/daily/uzs.json",
    "European Union:http://www.floatrates.com/daily/eur.json",
    "Canada:http://www.floatrates.com/daily/cad.json",
    "Comoros:http://www.floatrates.com/daily/kmf.json",
    "Algeria:http://www.floatrates.com/daily/dzd.json",
    "Armenia:http://www.floatrates.com/daily/amd.json",
    "Bahamas:http://www.floatrates.com/daily/bsd.json",
    "Barbados:http://www.floatrates.com/daily/bbd.json",
    "Belize:http://www.floatrates.com/daily/bzd.json",
    "Botswana:http://www.floatrates.com/daily/bwp.json",
    "Brunei:http://www.floatrates.com/daily/bnd.json",
    "Cambodia:http://www.floatrates.com/daily/khr.json",
    "French Polynesia:http://www.floatrates.com/daily/xpf.json",
    "China:http://www.floatrates.com/daily/cny.json",
    "Costa Rica:http://www.floatrates.com/daily/crc.json",    
    "Czech Republic:http://www.floatrates.com/daily/czk.json",
    "Dominican Republic:http://www.floatrates.com/daily/dop.json",
    "Eritrea:http://www.floatrates.com/daily/ern.json",
    "Gambia:http://www.floatrates.com/daily/gmd.json",
    "Gibraltar:http://www.floatrates.com/daily/gip.json",
    "Guyana:http://www.floatrates.com/daily/gyd.json",
    "Hong Kong:http://www.floatrates.com/daily/hkd.json",
    "India:http://www.floatrates.com/daily/inr.json",
    "Iraq:http://www.floatrates.com/daily/iqd.json",
    "Jordan:http://www.floatrates.com/daily/jod.json",
    "Kuwait:http://www.floatrates.com/daily/kwd.json",
    "Latvia:http://www.floatrates.com/daily/lvl.json",
    "Macau:http://www.floatrates.com/daily/mop.json",
    "Malawi:http://www.floatrates.com/daily/mwk.json",
    "Mauritania:http://www.floatrates.com/daily/mro.json",
    "Mexico:http://www.floatrates.com/daily/mxn.json",
    "Morocco:http://www.floatrates.com/daily/mad.json",
    "Namibia:http://www.floatrates.com/daily/nad.json",
    "New Taiwan:http://www.floatrates.com/daily/twd.json",
    "Nicaragua:http://www.floatrates.com/daily/nio.json",
    "Oman:http://www.floatrates.com/daily/omr.json",
    "Papua New Guinea:http://www.floatrates.com/daily/pgk.json",
    "Poland:http://www.floatrates.com/daily/pln.json",
    "Russia:http://www.floatrates.com/daily/rub.json",
    "Samoa:http://www.floatrates.com/daily/wst.json",
    "Serbia:http://www.floatrates.com/daily/rsd.json",
    "Singapore:http://www.floatrates.com/daily/sgd.json",
    "South Africa:http://www.floatrates.com/daily/zar.json",
    "Iceland2:http://www.floatrates.com/daily/ikr.json",
    "Eswatini:http://www.floatrates.com/daily/szl.json",
    "Tajikistan:http://www.floatrates.com/daily/tjs.json",
    "Tonga:http://www.floatrates.com/daily/top.json",
    "Turkey:http://www.floatrates.com/daily/try.json",
    "Ukraine:http://www.floatrates.com/daily/uah.json",
    "Vanuatu:http://www.floatrates.com/daily/vuv.json",
    "Vietnam:http://www.floatrates.com/daily/vnd.json",
    "Yemen:http://www.floatrates.com/daily/yer.json",
    "United Kingdom:http://www.floatrates.com/daily/gbp.json",
    "Japan:http://www.floatrates.com/daily/jpy.json",
    "Afghanistan:http://www.floatrates.com/daily/afn.json",
    "Angola:http://www.floatrates.com/daily/aoa.json",
    "Aruba:http://www.floatrates.com/daily/awg.json",
    "Bahrain:http://www.floatrates.com/daily/bhd.json",
    "Belarus2:http://www.floatrates.com/daily/byr.json",
    "Bolivia:http://www.floatrates.com/daily/bob.json",
    "Brazil:http://www.floatrates.com/daily/brl.json",
    "Bulgaria:http://www.floatrates.com/daily/bgn.json",
    "Cape Verde:http://www.floatrates.com/daily/cve.json",
    "Chile:http://www.floatrates.com/daily/clp.json",
    "Colombia:http://www.floatrates.com/daily/cop.json",
    "Croatia:http://www.floatrates.com/daily/hrk.json",
    "Denmark:http://www.floatrates.com/daily/dkk.json",
    "East Caribbean Dollar:http://www.floatrates.com/daily/xcd.json",
    "Ethiopia:http://www.floatrates.com/daily/etb.json",
    "Georgia:http://www.floatrates.com/daily/gel.json",
    "Guatemala:http://www.floatrates.com/daily/gtq.json",
    "Haiti:http://www.floatrates.com/daily/htg.json",
    "Hungary:http://www.floatrates.com/daily/huf.json",
    "Indonesia:http://www.floatrates.com/daily/idr.json",
    "Israel:http://www.floatrates.com/daily/ils.json",
    "Kazakhstan:http://www.floatrates.com/daily/kzt.json",
    "Kyrgyzstan:http://www.floatrates.com/daily/kgs.json",
    "Lebanon:http://www.floatrates.com/daily/lbp.json",
    "Libyan Arab Jamahiriya:http://www.floatrates.com/daily/lyd.json",
    "Macedonia, Republic of:http://www.floatrates.com/daily/mkd.json",
    "Malaysia:http://www.floatrates.com/daily/myr.json",
    "Mauritania2:http://www.floatrates.com/daily/mru.json",
    "Moldova, Republic of:http://www.floatrates.com/daily/mdl.json",
    "Mozambique:http://www.floatrates.com/daily/mzn.json",
    "Nepal:http://www.floatrates.com/daily/npr.json",
    "Turkmenistan:http://www.floatrates.com/daily/tmt.json",
    "Nigeria:http://www.floatrates.com/daily/ngn.json",
    "Pakistan:http://www.floatrates.com/daily/pkr.json",
    "Paraguay:http://www.floatrates.com/daily/pyg.json",
    "Peru:http://www.floatrates.com/daily/pen.json",
    "Qatar:http://www.floatrates.com/daily/qar.json",
    "Rwanda:http://www.floatrates.com/daily/rwf.json",
    "Sao Tome and Principe:http://www.floatrates.com/daily/stn.json",
    "Seychelles:http://www.floatrates.com/daily/scr.json",
    "Solomon Islands:http://www.floatrates.com/daily/sbd.json",
    "Korea (South):http://www.floatrates.com/daily/krw.json",
    "Sudan:http://www.floatrates.com/daily/sdg.json",
    "Sweden:http://www.floatrates.com/daily/sek.json",
    "Tanzania, United Republic of:http://www.floatrates.com/daily/tzs.json",
    "Trinidad and Tobago:http://www.floatrates.com/daily/ttd.json",
    "United Arab Emirates:http://www.floatrates.com/daily/aed.json",
    "Uruguay:http://www.floatrates.com/daily/uyu.json",
    "Cote d'Ivoire:http://www.floatrates.com/daily/xof.json",
    "Zambia:http://www.floatrates.com/daily/zmw.json"
};

std::vector<std::string> country_names = {
    "United States:usd.json",
    "Australia:aud.json",
    "Switzerland:chf.json",
    "Albania:all.json",
    "Argentina:ars.json",
    "Azerbaijan:azn.json",
    "Bangladesh:bdt.json",
    "Belarus:byn.json",
    "Bosnia and Herzegovina:bam.json",
    "Burundi:bif.json",
    "Central African Republic:xaf.json",
    "Congo, Democratic Republic of the:cdf.json",
    "Cuba:cup.json",
    "Djibouti:djf.json",
    "Egypt:egp.json",
    "Fiji:fjd.json",
    "Ghana:ghs.json",
    "Guinea:gnf.json",
    "Honduras:hnl.json",
    "Iceland:isk.json",
    "Iran:irr.json",
    "Jamaica:jmd.json",
    "Kenya:kes.json",
    "Laos:lak.json",
    "Lesotho:lsl.json",
    "Lithuania:ltl.json",
    "Madagascar:mga.json",
    "Maldives:mvr.json",
    "Mauritius:mur.json",
    "Mongolia:mnt.json",
    "Myanmar:mmk.json",
    "Netherlands Antilles:ang.json",
    "New Zealand:nzd.json",
    "Norway:nok.json",
    "Panama:pab.json",
    "Philippines:php.json",
    "Romania:ron.json",
    "El Salvador:svc.json",
    "Saudi Arabia:sar.json",
    "Sierra Leone:sll.json",
    "Somalia:sos.json",
    "South Sudan:ssp.json",
    "Suriname:srd.json",
    "Syria:syp.json",
    "Thailand:thb.json",
    "Tunisia:tnd.json",
    "Uganda:ugx.json",
    "Uzbekistan:uzs.json",
    "European Union:eur.json",
    "Canada:cad.json",
    "Comoros:kmf.json",
    "Algeria:dzd.json",
    "Armenia:amd.json",
    "Bahamas:bsd.json",
    "Barbados:bbd.json",
    "Belize:bzd.json",
    "Botswana:bwp.json",
    "Brunei:bnd.json",
    "Cambodia:khr.json",
    "French Polynesia:xpf.json",
    "China:cny.json",
    "Costa Rica:crc.json",
    "Czech Republic:czk.json",
    "Dominican Republic:dop.json",
    "Eritrea:ern.json",
    "Gambia:gmd.json",
    "Gibraltar:gip.json",
    "Guyana:gyd.json",
    "Hong Kong:hkd.json",
    "India:inr.json",
    "Iraq:iqd.json",
    "Jordan:jod.json",
    "Kuwait:kwd.json",
    "Latvia:lvl.json",
    "Macau:mop.json",
    "Malawi:mwk.json",
    "Mauritania:mro.json",
    "Mexico:mxn.json",
    "Morocco:mad.json",
    "Namibia:nad.json",
    "New Taiwan:twd.json",
    "Nicaragua:nio.json",
    "Oman:omr.json",
    "Papua New Guinea:pgk.json",
    "Poland:pln.json",
    "Russia:rub.json",
    "Samoa:wst.json",
    "Serbia:rsd.json",
    "Singapore:sgd.json",
    "South Africa:zar.json",
    "Iceland2:ikr.json",
    "Eswatini:szl.json",
    "Tajikistan:tjs.json",
    "Tonga:top.json",
    "Turkey:try.json",
    "Ukraine:uah.json",
    "Vanuatu:vuv.json",
    "Vietnam:vnd.json",
    "Yemen:yer.json",
    "United Kingdom:gbp.json",
    "Japan:jpy.json",
    "Afghanistan:afn.json",
    "Angola:aoa.json",
    "Aruba:awg.json",
    "Bahrain:bhd.json",
    "Belarus2:byr.json",
    "Bolivia:bob.json",
    "Brazil:brl.json",
    "Bulgaria:bgn.json",
    "Cape Verde:cve.json",
    "Chile:clp.json",
    "Colombia:cop.json",
    "Croatia:hrk.json",
    "Denmark:dkk.json",
    "East Caribbean Dollar:xcd.json",
    "Ethiopia:etb.json",
    "Georgia:gel.json",
    "Guatemala:gtq.json",
    "Haiti:htg.json",
    "Hungary:huf.json",
    "Indonesia:idr.json",
    "Israel:ils.json",
    "Kazakhstan:kzt.json",
    "Kyrgyzstan:kgs.json",
    "Lebanon:lbp.json",
    "Libyan Arab Jamahiriya:lyd.json",
    "Macedonia, Republic of:mkd.json",
    "Malaysia:myr.json",
    "Mauritania2:mru.json",
    "Moldova, Republic of:mdl.json",
    "Mozambique:mzn.json",
    "Nepal:npr.json",
    "Turkmenistan:tmt.json",
    "Nigeria:ngn.json",
    "Pakistan:pkr.json",
    "Paraguay:pyg.json",
    "Peru:pen.json",
    "Qatar:qar.json",
    "Rwanda:rwf.json",
    "Sao Tome and Principe:stn.json",
    "Seychelles:scr.json",
    "Solomon Islands:sbd.json",
    "Korea (South):krw.json",
    "Sudan:sdg.json",
    "Sweden:sek.json",
    "Tanzania, United Republic of:tzs.json",
    "Trinidad and Tobago:ttd.json",
    "United Arab Emirates:aed.json",
    "Uruguay:uyu.json",
    "Venezuela, Bolivarian Republic of:ves.json",
    "Cote d'Ivoire:xof.json",
    "Zambia:zmw.json"
};
